name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop existing containers
        run: docker compose down || echo "No containers running"

      - name: Start containers
        run: docker compose up -d
